### ISSUE TITLE
Function hashes change after being called

### ISSUE THREAD

**Issue by mhermher** [eddelbuettel/digest#92] opened 2018-09-27 18:57 UTC
Not sure if I am doing something wrong, but the hash of a function appears to change just by calling it. Self evident minimal example below:

`> rm(list=ls())
> fn <- function(){}
> digest::digest(fn)
[1] "21b49d838ee8307a99ec2e0c88af450d"
> fn()
NULL
> digest::digest(fn)
[1] "2cf2a04b8630ff5abb4f874e06384bbe"`

In case the enclosing environment is also a part of the hashed object, it should not have been altered here I believe.

**Comment by eddelbuettel** [comment] 2018-09-27 19:04
We just call `serialize()` and what you pass in. It is up to you to properly isolate things.  `digest()` does not alter you object...

**Comment by mhermher** [comment] 2018-09-27 20:46
Not sure if you completely understood me or if I completely understand you. Serialize() leads to the same output in both cases. The object has not been altered.

`> rm(list=ls())
> fn <- function(){}
> serialize(fn, NULL)
  [1] 58 0a 00 00 00 02 00 03 04 04 00 02 03 00 00 00 06 03 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66
 [41] 00 00 03 0d 00 00 00 08 00 00 00 01 00 00 00 07 00 00 00 01 00 00 00 12 00 00 00 07 00 00 00 12 00 00 00 01 00 00 00 01
 [81] 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 07 73 72 63 66 69 6c 65 00 00 00 04 00 00 00 00 00 00 00 f2 00 00 04 02 00
[121] 00 00 01 00 04 00 09 00 00 00 05 6c 69 6e 65 73 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 13 66 6e 20 3c 2d 20 66 75
[161] 6e 63 74 69 6f 6e 28 29 7b 7d 0a 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 08 66 69 6c 65 6e 61 6d 65 00 00 00 10 00
[201] 00 00 01 00 04 00 09 00 00 00 00 00 00 00 fe 00 00 00 fe 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 05 63 6c 61 73 73
[241] 00 00 00 10 00 00 00 02 00 04 00 09 00 00 00 0b 73 72 63 66 69 6c 65 63 6f 70 79 00 04 00 09 00 00 00 07 73 72 63 66 69
[281] 6c 65 00 00 00 fe 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00 00 00 fe
[321] 00 00 00 fe 00 00 00 fd 00 00 00 fe 00 00 02 06 00 00 04 02 00 00 01 ff 00 00 00 13 00 00 00 01 00 00 03 0d 00 00 00 08
[361] 00 00 00 01 00 00 00 11 00 00 00 01 00 00 00 11 00 00 00 11 00 00 00 11 00 00 00 01 00 00 00 01 00 00 04 02 00 00 02 ff
[401] 00 00 03 ff 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00 00 00 fe 00 00
[441] 04 02 00 00 02 ff 00 00 03 ff 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 0b 77 68 6f 6c 65 53 72 63 72 65 66 00 00 03
[481] 0d 00 00 00 08 00 00 00 01 00 00 00 00 00 00 00 01 00 00 00 12 00 00 00 00 00 00 00 12 00 00 00 01 00 00 00 01 00 00 04
[521] 02 00 00 02 ff 00 00 03 ff 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00
[561] 00 00 fe 00 00 00 fe 00 00 00 01 00 04 00 09 00 00 00 01 7b 00 00 00 fe
> digest::digest(fn)
[1] "21b49d838ee8307a99ec2e0c88af450d"
> fn()
NULL
> serialize(fn, NULL)
  [1] 58 0a 00 00 00 02 00 03 04 04 00 02 03 00 00 04 06 03 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66
 [41] 00 00 03 0d 00 00 00 08 00 00 00 01 00 00 00 07 00 00 00 01 00 00 00 12 00 00 00 07 00 00 00 12 00 00 00 01 00 00 00 01
 [81] 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 07 73 72 63 66 69 6c 65 00 00 00 04 00 00 00 00 00 00 00 f2 00 00 04 02 00
[121] 00 00 01 00 04 00 09 00 00 00 05 6c 69 6e 65 73 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 13 66 6e 20 3c 2d 20 66 75
[161] 6e 63 74 69 6f 6e 28 29 7b 7d 0a 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 08 66 69 6c 65 6e 61 6d 65 00 00 00 10 00
[201] 00 00 01 00 04 00 09 00 00 00 00 00 00 00 fe 00 00 00 fe 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 05 63 6c 61 73 73
[241] 00 00 00 10 00 00 00 02 00 04 00 09 00 00 00 0b 73 72 63 66 69 6c 65 63 6f 70 79 00 04 00 09 00 00 00 07 73 72 63 66 69
[281] 6c 65 00 00 00 fe 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00 00 00 fe
[321] 00 00 00 fe 00 00 00 fd 00 00 00 fe 00 00 02 06 00 00 04 02 00 00 01 ff 00 00 00 13 00 00 00 01 00 00 03 0d 00 00 00 08
[361] 00 00 00 01 00 00 00 11 00 00 00 01 00 00 00 11 00 00 00 11 00 00 00 11 00 00 00 01 00 00 00 01 00 00 04 02 00 00 02 ff
[401] 00 00 03 ff 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00 00 00 fe 00 00
[441] 04 02 00 00 02 ff 00 00 03 ff 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 0b 77 68 6f 6c 65 53 72 63 72 65 66 00 00 03
[481] 0d 00 00 00 08 00 00 00 01 00 00 00 00 00 00 00 01 00 00 00 12 00 00 00 00 00 00 00 12 00 00 00 01 00 00 00 01 00 00 04
[521] 02 00 00 02 ff 00 00 03 ff 00 00 04 02 00 00 06 ff 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 06 73 72 63 72 65 66 00
[561] 00 00 fe 00 00 00 fe 00 00 00 01 00 04 00 09 00 00 00 01 7b 00 00 00 fe
> digest::digest(fn)
[1] "2cf2a04b8630ff5abb4f874e06384bbe"`

**Comment by eddelbuettel** [comment] 2018-09-27 21:04
OTOH in a fresh session here:

```
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


Contrary to popular belief the speed of R's interpreter is rarely the limiting factor to
R's speed. People treating R like C is typically the limiting factor. You have vector
operations, USE THEM.
   -- Byron Ellis
      R-help (October 2005)

R> setwd('/home/XXX/')
R> library(digest)
R> fn <- function(){}
R> d1 <- digest(fn)
R> d2 <- digest(fn)
R> all.equal(d1, d2)
[1] TRUE
R> identical(d1, d2)
[1] TRUE
R> 
```

So cannot reproduce.

**Comment by eddelbuettel** [comment] 2018-09-27 21:06
It could be something as simple as byte-compilation on `fn` or whatnot -- something _outside the scope of digest_.  Up to you to keep inventory of the things you want hashed, and to keep them clean or dirty...

**Comment by eddelbuettel** [comment] 2018-09-27 21:31
Same on R 3.5.1, also under Linux. So cannot reproduce with r-release and r-oldred.

**Comment by mhermher** [comment] 2018-09-27 21:39
Hi Ed. Thanks for looking into it. You missed one critical part of this. You need to *call the function* in between the digest calls. That is what is triggering (somehow) the change in hash. I will be looking into it, so I will report back if I can track it down.

**Comment by eddelbuettel** [comment] 2018-09-27 21:47
It's Dirk.  But yes, that would do it, and that seems standard R behaviour to me.

Also:

```
R> digest(body(fn))
[1] "d4c8913085eca81e9da6944a7a46c993"
R> fn()
NULL
R> digest(body(fn))
[1] "d4c8913085eca81e9da6944a7a46c993"
R> 
```

I think we can close this.

**Comment by mhermher** [comment] 2018-09-27 22:07
Thanks Dirk, so you are saying that it does indeed appear to be byte-compiling the function in between the digest calls? The byte-compilation is causing it to change. Just want to understand. Don't really understand all this low-level R functionality, but want to understand how I can better use this.

**Comment by eddelbuettel** [comment] 2018-09-27 22:15
It sticks the calling environment in there, which got altered by calling _and receiving `NULL`_.

This is not the place for R language internal tutorials -- there is not bug in `digest`.  If you disagree, please document an actual bug and reopen.

**Closed by eddelbuettel** 2018-09-27 22:15 UTC
