### ISSUE TITLE
digest can't detect small change to large dataset

### ISSUE THREAD

**Issue by kendonB** [eddelbuettel/digest#97] opened 2019-04-20 18:10 UTC
I came across this issue in real life using the workflow package [drake](https://ropensci.github.io/drake/) which calls `digest` via the storage package [storr](http://richfitz.github.io/storr/). I had made a moderate change to one column of a 35 column and 29906368 row dataset (5GB in memory) and drake did not detect the change.

```r
# make a big dataset
big_iris = do.call(dplyr::bind_rows, rep(list(iris), 800000))

# make a minor change
big_iris2 = big_iris
big_iris2$Species[500000]
#> [1] setosa
#> Levels: setosa versicolor virginica
big_iris2$Species[500001]
#> [1] versicolor
#> Levels: setosa versicolor virginica
tmp = big_iris2$Species[500000]
big_iris2$Species[500000] = big_iris2$Species[500001]
big_iris2$Species[500001] = tmp
identical(big_iris, big_iris2)
#> [1] FALSE

# digest thinks they're the same
digest::digest(big_iris2) == digest::digest(big_iris)
#> [1] TRUE
```

<sup>Created on 2019-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```r
# md5 on disk thinks they're different
saveRDS(big_iris, "big_iris.rds", compress = FALSE)
saveRDS(big_iris2, "big_iris2.rds", compress = FALSE)
system("md5sum big_iris.rds")
#> b8905c3310958e4ddc3722326e40eca3 *big_iris.rds
system("md5sum big_iris2.rds")
#> 5c48f7cb1f21fdeb52937d1f3d30ffdf *big_iris2.rds
file.remove("big_iris.rds")
file.remove("big_iris2.rds")
```

Many thanks for this great and useful package. cc @wlandau @richfitz

**Comment by eddelbuettel** [comment] 2019-04-20 18:22
Insert shrug emoji -- we rely on proper serialization of the object by R.  That may affect `fastdigest` the same way.

Try to see if `serialize()` issues two identical or different objects.

**Comment by kendonB** [comment] 2019-04-20 18:27
```
> big_iris_ser = serialize(big_iris, NULL)
> big_iris2_ser = serialize(big_iris2, NULL)
> identical(big_iris_ser, big_iris2_ser)
[1] FALSE
```

**Comment by eddelbuettel** [comment] 2019-04-20 18:31
Interesting.  That looks like work for me then.  

Could you do me a favour and remove `tibble` (which does non-standard extensions to `data.frame` objects) from the equation?   Maybe just `rbind` a bazillions data.frame objects?   If/when that has an issue (without any other 3rd party packages) then we surely have a bug.

**Comment by kendonB** [comment] 2019-04-20 18:43
`big_iris = do.call(rbind, rep(list(iris), 800000))` takes ~infinite time, so hopefully `big_iris = do.call(dplyr::bind_rows, rep(list(iris), 800000))` is ok. I will change it above.

**Comment by kendonB** [comment] 2019-04-20 18:57
For reassurance:
``` r
medium_iris1 = do.call(dplyr::bind_rows, rep(list(iris), 800))
medium_iris2 = do.call(rbind, rep(list(iris), 800))
identical(medium_iris1, medium_iris2)
#> [1] TRUE
```

<sup>Created on 2019-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by eddelbuettel** [comment] 2019-04-20 19:13
You may not be aware of `data.table::rbindlist()` which is faster still:

```r
R> system.time(bigiris1 <- rbindlist(rep(list(iris), 10000)))
   user  system elapsed 
  0.051   0.007   0.059 
R> system.time(bigiris2 <- do.call(dplyr::bind_rows, rep(list(iris), 10000)))
   user  system elapsed 
  0.145   0.020   0.168 
R> system.time(bigiris3 <- do.call(rbind, rep(list(iris), 10000)))
   user  system elapsed 
 11.681   0.353  12.034 
R> 
```

**Comment by eddelbuettel** [comment] 2019-04-20 19:42
I can reproduce it with `N <- 800000`.

### Code

```r
## cf https://github.com/eddelbuettel/digest/issues/97

N <- 800000
library(digest)
library(data.table)

bi1 <- rbindlist(rep(list(iris), N))
bi2 <- copy(bi1)  # we know these are distinct

bi1 <- as.data.frame(bi1)
bi2 <- as.data.frame(bi2)

tmp <- bi2$Species[50000]
bi2$Species[50000] <- bi2$Species[50001]
bi2$Species[50001] <- tmp

print(i1 <- identical(bi1, bi2))
print(i2 <- identical(digest(bi1), digest(bi2)))
```

### Output

```r
edd@rob:~/git/digest(master)$ r issue97.R
[1] FALSE
[1] TRUE
edd@rob:~/git/digest(master)$ 
```

It is likely some large vector issue.  I'll flag it as help needed; I may not have time to dig into it but it may make a nice debugging project for somewhat motivated to fix this.

**Comment by kendonB** [comment] 2019-04-20 19:50
> It is likely some large vector issue.

The number of elements in the data.frame is still smaller than the large vector limit, but not substantially so.
```r
> 800000*150*3 / (2^31 - 1)
[1] 0.1676381
```

**Comment by kendonB** [comment] 2019-04-20 19:53
> It is likely some large vector issue.

The number of elements in the data.frame is still smaller than the large vector limit, but not substantially so:
```r
> ncol(big_iris)*nrow(big_iris) / (2^31 - 1)
[1] 0.2793968
```

**Comment by kendonB** [comment] 2019-04-20 19:55
@gmbecker, do you know how this might happen?

**Comment by eddelbuettel** [comment] 2019-04-20 20:55
> The number of elements in the data.frame is still smaller than the large vector limit, but not substantially so

Yes but ... 'inside' we loop by (raw ?) character returned by serialize.  Rows in the `data.frame` matter less methinks.  It's "merely" a big object I think.

**Comment by eddelbuettel** [comment] 2019-04-20 20:56
BTW there may also be a difference between the different algos.  You could try swapping `md5` for another.

**Comment by kendonB** [comment] 2019-04-20 23:10
Looks like switching out uint32's for R_xlen_t's works:

https://github.com/kendonB/digest/commit/69e214289b8a0442f06165a4173c3af5a22c68e7

```r
> print(i2 <- identical(digest(bi1, algo = "sha256_new"), digest(bi2, algo = "sha256_new")))
[1] FALSE
```

Should these be switched over for _all_ instances of these 32 bit integers throughout the package?

**Comment by eddelbuettel** [comment] 2019-04-20 23:24
Excellent stuff!  I had just noticed that you forked.

I would want us to be very careful.  I generally included 'reference' implementations of the algos, so if possibly I would be prefer to be minimal.  (I only looked at your diff for seconds yet though).

We should definitely make one or more of these 'bigger data' ready.  Would you be ok with doing it 'surgically' with  more minimal approach?

**Comment by eddelbuettel** [comment] 2019-04-20 23:29
Ie if we depart from

```c++
void sha256_process( sha256_context *ctx, uint8 data[64] )
{
    uint32 temp1, temp2, W[64];
    uint32 A, B, C, D, E, F, G, H;
...
```

then we're really only saying that what you found is an overrun in `uint32_t`.  That can happen.  And it is an inherent limitation in that implementation.

R's `x_len_t` is a little dirty as R has such a limited vocubulary (`int` at 32 bit, `double` at 64).  I would us rather plug in another, possibly new, hashing algo with a capacity for longer input then to muck with the known and trusted sha256 at its internals.

**Comment by kendonB** [comment] 2019-04-21 00:09
Would you consider just depending on `fastdigest` and having "spookyhash" being an option for algo?

**Comment by eddelbuettel** [comment] 2019-04-21 00:27
Unlikely on the added `Depends:`

```r
R> db <- tools::CRAN_package_db()
R> length(tools::dependsOnPkgs("digest", recursive=TRUE, installed=db))
[1] 3426
R> 
```

You just don't throw additonal dependencies at about 24% of CRAN.    Well, at least I won't.  Other people may.

As for adding an additional hashing algo here:  yes, that is what I suggested earlier, and what we have done quite consistently during the sixteen years this package has existed. Also see the other open issues.

**Comment by kendonB** [comment] 2019-04-21 18:27
See here for my start try trying to get spookyhash with incremental streaming moved over from fastdigest: https://github.com/kendonB/digest/commit/c0fe6ffef6e95969a230261ceac3e3cd8cb88607

I haven't figured out how to do the linking yet. The registration code in fastdigest is at the bottom of `serialize2.cpp` and in `init.c` in digest. I end up trying to include a cpp header file at the top of `init.c` and, of course, that doesn't work. Any help with registering the cpp functions in `init.c` would be very helpful.

**Comment by eddelbuettel** [comment] 2019-04-21 18:54
Cloned yours, and took a quick look.  We already had a wee bit of registration in `src/init.c` so I moved some stuff over.  With the minimal diff below it builds.  

```diff
diff --git a/DESCRIPTION b/DESCRIPTION
index a9260e7..e9de996 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -4,7 +4,7 @@ Author: Dirk Eddelbuettel <edd@debian.org> with contributions
  Mario Frasca, Bryan Lewis, Murray Stokely, Hannes Muehleisen,
  Duncan Murdoch, Jim Hester, Wush Wu, Qiang Kou, Thierry Onkelinx, 
  Michel Lang, Viliam Simko, Kurt Hornik and Radford Neal.
-Version: 0.6.18.2
+Version: 0.6.18.3
 Date: 2018-11-10
 Maintainer: Dirk Eddelbuettel <edd@debian.org>
 Title: Create Compact Hash Digests of R Objects
diff --git a/src/init.c b/src/init.c
index 054be3f..f80dfb0 100644
--- a/src/init.c
+++ b/src/init.c
@@ -21,17 +21,22 @@
 
 */
 
+#include <Rdefines.h>
 #include <R_ext/Rdynload.h>
 #include "xxhash.h"
 #include "pmurhash.h"
 
+SEXP R_spookydigest(SEXP s, SEXP fun);
+
 static const R_CallMethodDef callMethods [] = {
     { "PMurHash32", (DL_FUNC) &PMurHash32, 3 },
+    { "R_spookydigest", (DL_FUNC) &R_spookydigest, 2 },
     { NULL, NULL, 0 }
 };
 
 void R_init_digest(DllInfo *info) {
     R_RegisterCCallable("digest", "PMurHash32", (DL_FUNC) &PMurHash32);
+    R_RegisterCCallable("digest", "R_spookydigest", (DL_FUNC) &R_spookydigest);
 
     R_registerRoutines(info,
                        NULL,            /* slot for .C */
diff --git a/src/serialize2.cpp b/src/serialize2.cpp
index 0197688..92a5a95 100644
--- a/src/serialize2.cpp
+++ b/src/serialize2.cpp
@@ -44,7 +44,7 @@ static SEXP CallHook(SEXP x, SEXP fun)
 }
 
diff --git a/DESCRIPTION b/DESCRIPTION
index a9260e7..e9de996 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -4,7 +4,7 @@ Author: Dirk Eddelbuettel <edd@debian.org> with contributions
  Mario Frasca, Bryan Lewis, Murray Stokely, Hannes Muehleisen,
  Duncan Murdoch, Jim Hester, Wush Wu, Qiang Kou, Thierry Onkelinx, 
  Michel Lang, Viliam Simko, Kurt Hornik and Radford Neal.
-Version: 0.6.18.2
+Version: 0.6.18.3
 Date: 2018-11-10
 Maintainer: Dirk Eddelbuettel <edd@debian.org>
 Title: Create Compact Hash Digests of R Objects
diff --git a/src/init.c b/src/init.c
index 054be3f..f80dfb0 100644
--- a/src/init.c
+++ b/src/init.c
@@ -21,17 +21,22 @@
 
 */
 
+#include <Rdefines.h>
 #include <R_ext/Rdynload.h>
 #include "xxhash.h"
 #include "pmurhash.h"
 
+SEXP R_spookydigest(SEXP s, SEXP fun);
+
 static const R_CallMethodDef callMethods [] = {
     { "PMurHash32", (DL_FUNC) &PMurHash32, 3 },
+    { "R_spookydigest", (DL_FUNC) &R_spookydigest, 2 },
     { NULL, NULL, 0 }
 };
 
 void R_init_digest(DllInfo *info) {
     R_RegisterCCallable("digest", "PMurHash32", (DL_FUNC) &PMurHash32);
+    R_RegisterCCallable("digest", "R_spookydigest", (DL_FUNC) &R_spookydigest);
 
     R_registerRoutines(info,
                        NULL,            /* slot for .C */
diff --git a/src/serialize2.cpp b/src/serialize2.cpp
index 0197688..92a5a95 100644
--- a/src/serialize2.cpp
+++ b/src/serialize2.cpp
@@ -44,7 +44,7 @@ static SEXP CallHook(SEXP x, SEXP fun)
 }
 
```

Can you take it from here and clean up a bit more?   Nice work so far!

**Comment by eddelbuettel** [comment] 2019-04-21 19:24
Disregard that.  The registration is for other packages calling our C function.  Not relevant.  I changed the call to

```r
       val <- paste(.Call("R_spookydigest", object, ref_serializer, PACKAGE="digest"),
                     collapse="")
```

and that resolves but ... there is no `ref_serializer`.

**Comment by kendonB** [comment] 2019-04-21 20:39
I have worked it out and will put a PR together in the next few days with docs changes etc

**Comment by eddelbuettel** [comment] 2019-04-21 20:43
Great! 

Happy to do it incrementally.  So far one minor thing I'd change is the overly long `variable_holding_all_algorithm_names_for_streaming`.  Not that bad, but you get the drift  :)

How are you addressing the fact that while you now make `digest` suitable for "large" data, the default call in user packages like `drake` or `storr` may not yet use the right algo.  Separate later PRs for them?

**Comment by eddelbuettel** [comment] 2019-04-22 11:37
As I said, an incremental smaller approach may be preferable. I am not yet a fan of #98.

If I run #98 with the (now modifiied / generalised) test script it fixes things for several algos:

```sh
edd@rob:~/git/digest-streaming(master)$ r ../digest/issue97.R 
Data structures are not the same (good!) 
fastdigest :  not the same (good!) 
md5 : not the same (good!) 
sha1 : not the same (good!) 
crc32 : the same (wrong) 
sha256 : not the same (good!) 
sha512 : not the same (good!) 
xxhash32 : not the same (good!) 
xxhash64 : not the same (good!) 
murmur32 : the same (wrong) 
spookyhash : not the same (good!) 
edd@rob:~/git/digest-streaming(master)$
```

This suggests to me that maybe we want to split this into several PRs:
- one first important one with sufficient tests changing the line https://github.com/kendonB/digest/blob/1268b6acc3a03aa36bf3073f779d9cadbc182776/src/digest.c#L58  
- adding spookyhash if we think we need it

To me those are important but distinct changes.  We should not throw the first one in with the second.

**Comment by eddelbuettel** [comment] 2019-04-22 11:53
I just checked the one-line change and it 
1. passes unit tests (good!)
1. passes for your larger load on several hash (also good)

I suggest you make that a small PR.  Add ChangeLog as well if you could.  I don't think we can unit test it as not all machines will be large enough.

**Comment by wlandau** [comment] 2019-04-22 13:02
So glad to see plans to adopt `spookyhash` natively. Thank you for your work.

Re https://github.com/eddelbuettel/digest/issues/97#issuecomment-485281117, it will be trivially easy to change [`drake`'s default hash algorithm](https://github.com/ropensci/drake/blob/efbc8586c599b4396e714c727060340b71263f00/R/api-cache.R#L500), and preexisting projects will remain unaffected. `storr` looks similar, though I cannot speak for @richfitz.

**Comment by eddelbuettel** [comment] 2019-04-22 13:58
> So glad to see plans to adopt spookyhash natively. 

Not sure if you're aware put the last three of so hashes may all have been user contributed.  The door is always open.  See also the other issues.

But we have to be careful in how we make changes the package is used fairly widely.   And as I show above, with propose one-word change to the length counter helps with the default hasher too so you or other downstreams don't have to change anything.   You can, of course, but always better not to force it.

**Comment by kendonB** [comment] 2019-04-22 16:51
Not as simple on Windows:

```r
## cf https://github.com/eddelbuettel/digest/issues/97

if("digest" %in% installed.packages()) remove.packages("digest")
tools::assertError(library(digest))
remotes::install_github("kendonb/digest@patch-1")

cat("OS: ", Sys.info()["sysname"], "\n")

N <- 800000
#N <- 80000
library(digest)
library(data.table)

bi1 <- rbindlist(rep(list(iris), N))
bi2 <- copy(bi1)  # we know these are distinct

bi1 <- as.data.frame(bi1)
bi2 <- as.data.frame(bi2)

tmp <- bi2$Species[500000]
bi2$Species[500000] <- bi2$Species[500001]
bi2$Species[500001] <- tmp

textOnBool <- function(b) if (b) "the same (wrong)" else "not the same (good!)"

i1 <- identical(bi1, bi2)
cat("Data structures are", textOnBool(i1), "\n")
i0 <- identical(fastdigest::fastdigest(bi1), fastdigest::fastdigest(bi2))
cat("fastdigest : ", textOnBool(i0), "\n")
for (a in c("md5", "sha1", "crc32", "sha256", "sha512",
            "xxhash32", "xxhash64", "murmur32")) {
  cat(a, ": ")
  i2 <- identical(digest(bi1, algo=a), digest(bi2, algo=a))
  cat(textOnBool(i2), "\n")
}
```

```
$ Rscript.exe issue97.R
Downloading GitHub repo kendonb/digest@patch-1
   checking for file 'C:\Users\kmbel\AppData\Local\Temp\Rtmp8k1NP8\remotes29143a   checking for file 'C:\Users\kmbel\AppData\Local\Temp\Rtmp8k1NP8\remotes29143av  checking for file 'C:\Users\kmbel\AppData\Local\Temp\Rtmp8k1NP8\remotes29143ab868ee\kendonB-digest-008f71f/DESCRIPTION' (421ms)
-  preparing 'digest':
......install code.....
*** arch - x64
* DONE (digest)
In R CMD INSTALL
OS:  Windows
Warning message:
package 'data.table' was built under R version 3.5.3
Data structures are not the same (good!)
fastdigest :  not the same (good!)
md5 : the same (wrong)
sha1 : the same (wrong)
crc32 : the same (wrong)
sha256 : the same (wrong)
sha512 : not the same (good!)
xxhash32 : not the same (good!)
xxhash64 : not the same (good!)
murmur32 : the same (wrong)
```

Is there some equivalent of `// [[Rcpp::plugins(cpp11)]]` for a non Rcpp package? Ref: https://github.com/RcppCore/Rcpp/issues/460

**Comment by eddelbuettel** [comment] 2019-04-22 17:00
Glad you checked.  

The plugin works the same, it just adds the flag.  Older compiler though -- whatever Rtools has.  

The difference (on Windows) has me confused.  I don't quite know what to make of that.

**Comment by kendonB** [comment] 2019-04-22 17:15
My original test version (with sha256_new replacing all 32 bit integers in sha256 with R_xlen_t) also used this same Windows machine and worked, FYI.

**Comment by kendonB** [comment] 2019-04-22 17:17
Tested with the CRAN version and it still looks like the change helps a bit:
```
Data structures are not the same (good!)
fastdigest :  not the same (good!)
md5 : the same (wrong)
sha1 : the same (wrong)
crc32 : the same (wrong)
sha256 : the same (wrong)
sha512 : the same (wrong)
xxhash32 : the same (wrong)
xxhash64 : the same (wrong)
murmur32 : the same (wrong)
```

**Comment by kendonB** [comment] 2019-04-22 20:19
See here for the minimal changes required to get md5sum to work on (my) Windows. I'm guessing on linux the `unsigned long int` actually becomes an `unsigned long long int`?

https://github.com/kendonB/digest/compare/patch-1...kendonB:testmd5?expand=1

Would you accept PRs along these lines to make this and other algos work for long vectors?

**Comment by eddelbuettel** [comment] 2019-04-22 20:40
Oh yes that is starting to ring a bell -- is your windows 32 bit or 64 bit?

**Comment by kendonB** [comment] 2019-04-22 23:52
My Windows is 64-bit.

**Comment by kendonB** [comment] 2019-04-23 05:12
> in short I don't think we can just swap int32 for int64 types

What would convince you that we can just swap them?

**Comment by eddelbuettel** [comment] 2019-04-23 10:17
Upstream :)  Or an equivalent full-blown crypto analysis.  Or some more time and some other people weighing in.  For now it is more important to me than we correspond to genuine sha256.  Let's not rush.  (And your idea of a 'new' sha256 is still good too.)

**Comment by kendonB** [comment] 2019-04-24 04:59
Asking for some other people to weigh in:
https://stackoverflow.com/questions/55822124/is-swapping-uint32-for-uint64-benign-other-than-possibly-memory-usage/55822532#55822532

**Comment by eddelbuettel** [comment] 2019-04-24 11:36
One thing that came to mind is that the (highly efficient) algorithm often use bitmap and bitwise transform for the key parts.  That you can't just swap.  A counter/loop variable, yes.  The actual encoding, probably not so much,

**Comment by eddelbuettel** [comment] 2019-04-24 11:37
> But modifying crypto libraries is not a casual acitvity, even buggy implementations of deprecated alogorithms.

Amen.

**Comment by eddelbuettel** [comment] 2019-05-26 21:18
I think we can close this one with version 0.6.19 on CRAN.

**Closed by eddelbuettel** 2019-05-26 21:18 UTC
Labels: help wanted

**Comment by kendonB** [comment] 2019-05-26 21:34
This one is still not solved on Windows, though that might change with the coming compiler changes in RTools.

**Comment by eddelbuettel** [comment] 2019-05-26 22:07
Shall we reopen?

**Comment by kendonB** [comment] 2019-05-27 23:40
This one works for md5 and is just altering the counting variables:

https://github.com/eddelbuettel/digest/compare/master...kendonB:md5_counter_change?expand=1

**Comment by eddelbuettel** [comment] 2019-05-27 23:47
I am uneasy about changingf `uint32_t` to `uint64_t`. I would prefer not to.

**Comment by kendonB** [comment] 2019-05-28 01:56
I think the options are:

1. Do nothing.
2. Do nothing and update the documentation with caveats.
3. ~~Apply fixes like mine with a bunch of testing including changes to the last bits of >4GB objects across platforms.~~
4. Add "experimental" algos for those that break on Windows that users can switch at their peril.
5. Wait for RTools 4.0 and see if that fixes things.
6. Dig around to find alternative newer implementations of the algos to bring them up to date. I think I recall, for example, that the current implementation of `md5sum` on Ubuntu is a different source to that in digest.

**Comment by eddelbuettel** [comment] 2019-05-28 02:14
Good list.  We could also just say that the reference implementation uses 32 bit unsigned -- which imposes a limit. 

If someone care enough about `md5sum` on single objects in excess of 4gb on Windows, well, yes, then we may not serve themiour.  It wasn't so long that 2gb was a limit for single files so not too many crocodile tears from me. 

The route of opening more experimental digesters is good too.  I simply want to remain conservative with the published default behaviour.
