### ISSUE TITLE
implement tests for all algos using `serialize = TRUE`?

### ISSUE THREAD

**Issue by kendonB** [eddelbuettel/digest#101] opened 2019-04-29 14:56 UTC
Currently, it looks like the tests of in-memory objects all use `serialize = FALSE`. This doesn't test for stability over time if the serialization headers associated with object types change.

- [ ] md5
- [ ] sha1
- [ ] crc32
- [ ] sha256
- [ ] sha512
- [ ] xxhash32
- [ ] xxhash64
- [ ] murmur32

Might only be necessary for a single algo.

**Comment by eddelbuettel** [comment] 2019-04-29 14:59
Well digest is old and has been through the 'v1 -> v2' change, and now the 'v3' change.  I am less worried about R changes.  They happen, and I have no control --- that is all R Core.  And I trust them.

So not testing for that is more-or-less by design.   I am more concerned with other inadvertent changes affecting the hash functions.

**Comment by kendonB** [comment] 2019-04-29 15:22
Is it something you'd want to be able to flag for users though? Is it also possible that there might also be platform differences within versions that could cause differences in the headers?

**Comment by eddelbuettel** [comment] 2019-04-29 15:27
But that is where R shines.  Its (fourteen bytes or whatever it is) header _is_ portable across machines, OS, and whatnot.  Untile they change it, which they do (give or take) once a decade as _e.g._  R 3.6.0 just gave a new rds format to support ALTREP (and I don't recall if it changed serialization).  

Also (at least some) platform difference we already cover as we use the same reference output for every platform CRAN tests on.

**Comment by CorradoLanera** [comment] 2021-01-06 01:22
I discovered today that something changed between R3.6 and R4.0, and a data frame I have `digest()`ed (without customizing any options) last year, now returns a different result :face_with_head_bandage: (tested switching between the two version of R, same version of `{digest}`, the output are different).

**Comment by eddelbuettel** [comment] 2021-01-06 01:29
You provided no reproducible example leaving us to guess but ... for example if your `data.frame` had a `factor` column that is now handled differently _by R itself_ and all that is clearly signalled in the R NEWS file and alike.  In short, *you* are supposed to take care of your input data, `digest()` will not guess it for you.

That said, my guess could be off but again -- hard to say anything without reproducible code.

**Comment by CorradoLanera** [comment] 2021-01-06 10:43
You are right! Sorry. 
As usual, trying to create a reprex quite helped me debug it: the keys for the solution are your guess and the try to make the reprex minimal. In the first place, I checked my dataset (in my reference environment: R 3.6.2), which has a single factor variable. Removing it, the two `digest()`s were the same. So, I thought you are right and started to answer my apologies. I cannot post the dataset, so I decide to create a minimal simple one for others' benefit. And I have tried the following:

``` r
# R 3.6.2
foo <- data.frame(
  a = factor(1:2),
  b = 1:2
)
digest::digest(foo)
#> [1] "886d5b07c086dc4a9adb7b0dc22b7a58"
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


``` r
#  R 4.0.3
foo <- data.frame(
  a = factor(1:2),
  b = 1:2
)
digest::digest(foo)
#> [1] "886d5b07c086dc4a9adb7b0dc22b7a58"
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


So... that was strange to me because I expected the two `digest()`s were different from each other (and I post that here as an example that your `digest()` doesn't seem to have a problem with factors across R 3.6 and 4.0). So I decide to provide a two-rows `dput()` of my dataset, purged from all the not relevant (to reproduce the problem) variables... and I found the issue was maybe less complicated (and I know it before!) but maybe more subtle: the dataset was imported in R by `foreign::read.spss()` with the option `to.data.frame = TRUE`... which clearly relay on the famous `stringsAsFactors`'s default option... so... the problem doesn't be "the" factor itself (not it's internal representation) but the fact that in R 4.0 that column was not imported as a factor at all :smile: 

So, thank you very much for your time and guess. I am happy to be at least useful in checking that `digest()` doesn't seem to have a problem with factors between R 3.6 and 4.0.

**Comment by eddelbuettel** [comment] 2021-01-06 13:08
Thanks for detailed follow-up, much appreciated.  I'll close this as there is no "issue" to address and search engine / folks looking at all tickets will still get it.

**Closed by eddelbuettel** 2021-01-06 13:08 UTC
