### ISSUE TITLE
hope to address file.access issue, without adding dependencies

### ISSUE THREAD

**Issue by ashlinrichardson** [eddelbuettel/digest#149] opened 2020-02-29 00:51 UTC
Dear Eddel Buettel,
Sir:

Thank you for your excellent software! @boshek pointed out that at line 170 of
https://github.com/eddelbuettel/digest/blob/master/R/digest.R

there's a potential minor improvement, since file.access() isn't reliable for distributed systems

At https://github.com/eddelbuettel/digest/issues/49
you noted that adding more dependencies would not be a solution at all-- and I would certainly agree with your view.

Would you be open to a PR that would implement the minor improvement, without adding any dependencies?

Thanks for considering this

Many thanks
cheers,

Ashlin Richardson
Senior Data Scientist
Government of British Columbia
Victoria, BC Canada

**Comment by eddelbuettel** [comment] 2020-02-29 06:54
Hi @Ashlin, 

What exactly are you suggesting? If it is this line
https://github.com/eddelbuettel/digest/blob/b0f04b4f67865f79e01253b351f009db8495e582/R/digest.R#L170
then I have to refer you to R itself as we discussed in #49 -- and eg confirmed by @HenrikBengtsson .  This is not a shortcoming in the `digest` package, so it should preferably be addressed where it belongs, in R itself.  Or in your application layer: if the shared drive does not support POSIX semantics, copy the file to your local machine and its filesystem and then call `digest`.

What would be the "fix" for this you are contemplating?  If it is simple and small  we can consider it if it doesn't have side effects -- though I still think "fixing symptoms" is bad/wrong.  

Dirk

**Comment by ashlinrichardson** [comment] 2020-02-29 07:37
@eddelbuettel 

Hi Dirk, 
Yes, agreed--
--not hoping to mask symptoms of a problem that's in R,

rather I was hoping to align with the spirit of your extensive work on the Rcpp and inline packages, by perhaps getting a little closer to the horse's mouth:

by using an R call that's slightly more direct or reliable:
        file()

Wanting to develop things like Rcpp shows great care, attention to detail and perseverance,  so I thought a change to a lower-level function that's more stable across platforms, might be of interest

Will attach a PR in moment to illustrate-- even if you like the idea -- you're likely to be able to express it better or more concisely than I am
cheers,

Ash

**Comment by eddelbuettel** [comment] 2020-02-29 13:21
No don't attach PR.  Bring is *here* because *here* is where we have the discussion.

And maybe also try to address the _qualitative_ issue from the prior (closed !!) issue on the _very same topic_.  So far you have not addded anything new to the debate.

**Comment by eddelbuettel** [comment] 2020-03-07 21:37
I have given this some more thought, and decided to close this and not alter digest.

I have no doubt that the issue is frustrating you in your use case of access to your network share. Altering the code for every user digest in however not the right response.  If I were you I'd try to 'mask' or 'shadow' digest with a local variant that first copies a file to a local tempfile (ie `C:\TEMP`, say) where the semantics are not broken.   Or else read the content and call digest() on the data, rather than the file.

**Closed by eddelbuettel** 2020-03-07 21:37 UTC
